import {
  LaborTask,
  LaborMaterial,
  FeatureType,
} from "../../interfaces/laborTypes";

export const floorOptions = [1, 2, 3, 4];

export const featureTypes: { value: FeatureType; label: string }[] = [
  { value: "windows", label: "Windows" },
  { value: "walls", label: "Walls" },
  { value: "doors", label: "Doors" },
  { value: "closets", label: "Closets" },
  { value: "crownMolding", label: "Crown Molding" },
  { value: "chairRail", label: "Chair Rail" },
  { value: "baseboard", label: "Baseboard" },
  { value: "wainscoting", label: "Wainscoting" },
];

export const laborMaterials: Record<string, LaborMaterial> = {
  caulking: {
    name: "Caulking",
    description: "Acrylic latex caulk for sealing gaps and cracks",
    quantity: 1,
    unit: "tube",
    price: 6,
  },
  dropCloths: {
    name: "Drop Cloths",
    description: "Large drop cloth to protect floors and furniture",
    quantity: 1,
    unit: "large",
    price: 10,
  },
  drywallCompound: {
    name: "Drywall Compound",
    description: "Drywall compound for finishing seams",
    quantity: 1,
    unit: "bucket",
    price: 12,
  },
  drywallTape: {
    description: "Drywall tape for reinforcing seams",
    quantity: 1,
    unit: "roll",
    price: 2,
  },
  maskingPaper: {
    name: "Masking Paper",
    description: "Masking paper for protecting surfaces during painting",
    quantity: 2,
    unit: "rolls",
    price: 3,
  },
  cornerBead: {
    name: "Corner Bead",
    description: "Corner bead for drywall installation",
    quantity: 1,
    unit: "piece",
    price: 5,
  },
  sandingSponges: {
    name: "Sanding Sponges",
    description: "Sanding sponges for smoothing surfaces",
    quantity: 2,
    unit: "pieces",
    price: 4,
  },
  drywallScrews: {
    name: "Drywall Screws",
    description: "Drywall screws for fastening drywall",
    quantity: 1,
    unit: "box",
    price: 6,
  },
  mixingStick: {
    name: "Mixing Stick",
    description: "Mixing stick for drywall compound",
    quantity: 1,
    unit: "piece",
    price: 0,
  },
  dustMask: {
    name: "Dust Mask",
    description: "Dust mask for protection during sanding",
    quantity: 1,
    unit: "piece",
    price: 3,
  },
  extensionPole: {
    name: "Extension Pole",
    description: "Extension pole for reaching high areas",
    quantity: 1,
    unit: "piece",
    price: 0,
  },
  gloves: {
    name: "Gloves",
    description: "Protective gloves for hand safety",
    quantity: 2,
    unit: "pairs",
    price: 5,
  },
  ladder: {
    name: "Ladder",
    description: "Ladder for reaching high places",
    quantity: 1,
    unit: "piece",
    price: 0,
  },
  paint: {
    name: "Paint",
    description: "Interior paint for walls and ceilings",
    quantity: 2,
    unit: "gallons",
    price: 30,
  },
  paintBrushes: {
    name: "Paint Brushes",
    description: "Brushes for detailed painting work",
    quantity: 2,
    unit: "pieces",
    price: 7,
  },
  paintRollers: {
    name: "Paint Rollers",
    description: "Rollers for painting large areas",
    quantity: 2,
    unit: "pieces",
    price: 10,
  },
  paintTray: {
    name: "Paint Tray",
    description: "Tray for holding paint while working",
    quantity: 1,
    unit: "piece",
    price: 0,
  },
  plasticSheeting: {
    name: "Plastic Sheeting",
    description: "Plastic sheeting for protecting surfaces",
    quantity: 1,
    unit: "roll",
    price: 15,
  },
  primer: {
    name: "Primer",
    description: "Primer for preparing surfaces for paint",
    quantity: 1,
    unit: "gallon",
    price: 15,
  },
  puttyKnife: {
    name: "Putty Knife",
    description: "Putty knife for applying and smoothing compound",
    quantity: 1,
    unit: "piece",
    price: 0,
  },
  sandpaper: {
    name: "Sandpaper",
    description: "Sandpaper for smoothing surfaces",
    quantity: 5,
    unit: "sheets",
    price: 1,
  },
  spackle: {
    name: "Spackle",
    description: "Spackle for filling small holes and imperfections",
    quantity: 1,
    unit: "small tub",
    price: 0,
  },
  sprayer: {
    name: "Sprayer",
    description: "Sprayer for applying paint or primer",
    quantity: 1,
    unit: "piece",
    price: 0,
  },
  tape: {
    name: "Tape",
    description: "Tape for masking off areas during painting",
    quantity: 2,
    unit: "rolls",
    price: 3,
  },
  detergentOrSoap: {
    name: "Detergent or Soap",
    description: "Detergent or soap for cleaning surfaces",
    quantity: 1,
    unit: "bottle",
    price: 5,
  },
  ragsAndMicrofiberCloths: {
    name: "Rags and Microfiber Cloths",
    description: "Rags and microfiber cloths for cleaning surfaces",
    quantity: 1,
    unit: "set",
    price: 10,
  },
};

export const availableLaborTasks: LaborTask[] = [
  {
    name: "Caulking",
    description: "Caulking gaps and cracks around trim and fixtures",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [laborMaterials.caulking, laborMaterials.gloves],
  },
  {
    name: "Cleaning",
    description: "Cleaning walls and surfaces to prepare for painting",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [
      laborMaterials.gloves,
      laborMaterials.detergentOrSoap,
      laborMaterials.ragsAndMicrofiberCloths,
    ],
  },
  {
    name: "Remove Old Paint or Wallpaper",
    description: "Scraping and sanding old paint from surfaces",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Stain or varnish",
    description: "Applying stain or varnish to wood surfaces",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paintBrushes,
      laborMaterials.gloves,
      laborMaterials.dropCloths,
    ],
  },
  {
    name: "Drywall Tape",
    description: "Taping seams and joints in drywall",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [laborMaterials.drywallTape],
  },
  {
    name: "Move Furniture",
    description: "Moving furniture out of the room or to the center",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [],
  },
  {
    name: "Cover Furniture",
    description: "Covering furniture to protect it during painting",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [
      laborMaterials.dropCloths,
      laborMaterials.plasticSheeting,
      laborMaterials.tape,
    ],
  },
  {
    name: "Remove Wall Decor",
    description: "Removing pictures, mirrors, and other wall decor",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [laborMaterials.gloves, laborMaterials.dustMask],
  },
  {
    name: "Mask Fixtures",
    description:
      "If decor can't be removed, masking off fixtures to protect them during painting",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [laborMaterials.tape, laborMaterials.plasticSheeting],
  },
  {
    name: "Fix Small Holes",
    description: "Includes nail holes and minor imperfections",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.spackle,
      laborMaterials.sandpaper,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Fix Large Holes",
    description: "Includes large holes and significant damage",
    hours: 3,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.drywallCompound,
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Sanding",
    description: "Sanding walls and ceilings to prepare for painting",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Drywall Replacement",
    description:
      "Includes repairing or replacing damaged drywall like replacing sections or screwing in new drywall",
    hours: 3,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.drywallCompound,
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Priming",
    description: "Applying primer to surfaces before painting",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.primer,
      laborMaterials.paintBrushes,
      laborMaterials.paintRollers,
      laborMaterials.paintTray,
      laborMaterials.extensionPole,
      laborMaterials.ladder,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Wood Root Repair",
    description: "Repairing wood rot on trim or other wood surfaces",
    hours: 3,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.drywallCompound,
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Popcorn Removal",
    description: "Removing popcorn ceiling texture",
    hours: 4,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.dustMask,
      laborMaterials.gloves,
      laborMaterials.dropCloths,
      laborMaterials.plasticSheeting,
      laborMaterials.tape,
      laborMaterials.puttyKnife,
      laborMaterials.sandpaper,
    ],
  },
  {
    name: "Apply Texture",
    description: "Applying texture",
    hours: 3,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
      laborMaterials.sprayer,
    ],
  },
  {
    name: "Paint Walls",
    description: "Applying paint to walls",
    hours: 3,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paint,
      laborMaterials.paintBrushes,
      laborMaterials.paintRollers,
      laborMaterials.paintTray,
      laborMaterials.extensionPole,
      laborMaterials.ladder,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Paint Ceilings",
    description: "Applying paint to ceilings",
    hours: 3,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paint,
      laborMaterials.paintBrushes,
      laborMaterials.paintRollers,
      laborMaterials.paintTray,
      laborMaterials.extensionPole,
      laborMaterials.ladder,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Paint Doors",
    description: "Applying paint to doors",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paint,
      laborMaterials.paintBrushes,
      laborMaterials.gloves,
      laborMaterials.dropCloths,
    ],
  },
  {
    name: "Paint Closets",
    description: "Applying paint to closet interiors",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paint,
      laborMaterials.paintBrushes,
      laborMaterials.gloves,
      laborMaterials.dropCloths,
    ],
  },
  {
    name: "Paint Trim",
    description: "Applying paint to trim and moldings",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paint,
      laborMaterials.paintBrushes,
      laborMaterials.gloves,
      laborMaterials.dropCloths,
    ],
  },
  {
    name: "Final Cleanup",
    description: "Cleaning up the work area after painting is complete",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [laborMaterials.gloves],
  },
];
