import { LaborTask, LaborMaterial, FeatureType } from "./laborTypes";

export const floorOptions = [1, 2, 3, 4];

export const featureTypes: { value: FeatureType; label: string }[] = [
  { value: "windows", label: "Windows" },
  { value: "walls", label: "Walls" },
  { value: "doors", label: "Doors" },
  { value: "closets", label: "Closets" },
  { value: "crownMolding", label: "Crown Molding" },
  { value: "chairRail", label: "Chair Rail" },
  { value: "baseboard", label: "Baseboard" },
  { value: "wainscoting", label: "Wainscoting" },
];

export const laborMaterials: Record<string, LaborMaterial> = {
  gloves: { quantity: 2, unit: "pairs", price: 5 },
  dropCloths: { quantity: 1, unit: "large", price: 10 },
  plasticSheeting: { quantity: 1, unit: "roll", price: 15 },
  tape: { quantity: 2, unit: "rolls", price: 3 },
  sandpaper: { quantity: 5, unit: "sheets", price: 1 },
  puttyKnife: { quantity: 1, unit: "piece", price: 0 },
  spackle: { quantity: 1, unit: "small tub", price: 0 },
  drywallCompound: { quantity: 1, unit: "bucket", price: 12 },
  primer: { quantity: 1, unit: "gallon", price: 15 },
  cleaningSupplies: { quantity: 1, unit: "set", price: 20 },
  drywallTape: { quantity: 1, unit: "roll", price: 2 },
  caulking: { quantity: 1, unit: "tube", price: 6 },
  dustMask: { quantity: 1, unit: "piece", price: 3 },
  paint: { quantity: 2, unit: "gallons", price: 30 },
  paintBrushes: { quantity: 2, unit: "pieces", price: 7 },
  paintRollers: { quantity: 2, unit: "pieces", price: 10 },
  paintTray: { quantity: 1, unit: "piece", price: 0 },
  extensionPole: { quantity: 1, unit: "piece", price: 0 },
  ladder: { quantity: 1, unit: "piece", price: 0 },
  sprayer: { quantity: 1, unit: "piece", price: 0 },
};

export const availableLaborTasks: LaborTask[] = [
  {
    name: "Drywall Tape",
    description: "Taping seams and joints in drywall",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [laborMaterials.drywallTape],
  },
  {
    name: "Move Furniture",
    description: "Moving furniture out of the room or to the center",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [],
  },
  {
    name: "Cover Furniture",
    description: "Covering furniture to protect it during painting",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [
      laborMaterials.dropCloths,
      laborMaterials.plasticSheeting,
      laborMaterials.tape,
    ],
  },
  {
    name: "Remove Wall Decor",
    description: "Removing pictures, mirrors, and other wall decor",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [laborMaterials.gloves, laborMaterials.dustMask],
  },
  {
    name: "Mask Fixtures",
    description:
      "If decor can't be removed, masking off fixtures to protect them during painting",
    hours: 1,
    rate: 30,
    amountOfLabor: 0,
    laborMaterials: [laborMaterials.tape, laborMaterials.plasticSheeting],
  },
  {
    name: "Fix Small Holes",
    description: "Includes nail holes and minor imperfections",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.spackle,
      laborMaterials.sandpaper,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Fix Large Holes",
    description: "Includes large holes and significant damage",
    hours: 3,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.drywallCompound,
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Sanding",
    description: "Sanding walls and ceilings to prepare for painting",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Drywall Repairs",
    description:
      "Includes repairing damaged drywall like replacing sections or screwing in new drywall",
    hours: 3,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.puttyKnife,
      laborMaterials.drywallCompound,
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Priming",
    description: "Applying primer to surfaces before painting",
    hours: 2,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.primer,
      laborMaterials.paintBrushes,
      laborMaterials.paintRollers,
      laborMaterials.paintTray,
      laborMaterials.extensionPole,
      laborMaterials.ladder,
      laborMaterials.gloves,
    ],
  },
  {
    name: "Popcorn Removal",
    description: "Removing popcorn ceiling texture",
    hours: 4,
    rate: 30,
    amountOfLabor: 3,
    laborMaterials: [
      laborMaterials.dustMask,
      laborMaterials.gloves,
      laborMaterials.dropCloths,
      laborMaterials.plasticSheeting,
      laborMaterials.tape,
      laborMaterials.puttyKnife,
      laborMaterials.sandpaper,
    ],
  },
  {
    name: "Apply Texture",
    description: "Applying texture",
    hours: 3,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.sandpaper,
      laborMaterials.dustMask,
      laborMaterials.gloves,
      laborMaterials.sprayer,
    ],
  },
  {
    name: "Painting",
    description: "Applying paint",
    hours: 3,
    rate: 30,
    amountOfLabor: 1,
    laborMaterials: [
      laborMaterials.paint,
      laborMaterials.paintBrushes,
      laborMaterials.paintRollers,
      laborMaterials.paintTray,
      laborMaterials.extensionPole,
      laborMaterials.ladder,
      laborMaterials.gloves,
    ],
  },
];
